/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexLLLMathlib.Interval
public import HexLLLMathlib.State
public import HexLLLMathlib.Bridge
public import HexLLLMathlib.Checker
public import HexLLLMathlib.Reducer
public import HexLLLMathlib.ShortVector

public section

/-!
The `HexLLLMathlib` library identifies the executable `HexLLL` lattice
surface with Mathlib's linear-algebra API.

This library exposes a `Submodule ℤ` model of the integer row lattice
generated by an executable `Hex.Matrix`, together with the equivalence between
Mathlib-side submodule membership and the executable `Hex.Matrix.memLattice`
predicate used by `hex-lll`, and the Euclidean short-vector guarantee for
`Hex.lll`.
-/
