module

public import HexLLL.Basic
public import HexLLLMathlib.Interval
public import HexGramSchmidtMathlib.Int
public import HexMatrixMathlib.RankSpanNullspace
public import Mathlib.Analysis.InnerProductSpace.GramSchmidtOrtho

public section

/-!
Mathlib-side correspondence lemmas for the lattice surface of `hex-lll`.

This module packages the integer row lattice generated by an executable
`Hex.Matrix` as a Mathlib `Submodule ℤ`, then relates membership in that
submodule to the executable `Hex.Matrix.memLattice` predicate used by
`HexLLL`.  It also states the Mathlib-side Euclidean norm version of the
LLL short-vector guarantee for an already reduced basis.
-/

namespace HexLLLMathlib

/-- The canonical `LLLState` constructor packages the executable Gram-Schmidt
data. Lives on the Mathlib side because the diagonal Gram-determinant
identification (`gramDetVec_eq_gramDet`) consumes a `StepWitness b`, which is
supplied by `StepWitness.ofGram`. -/
theorem LLLState.ofBasis_valid (b : Hex.Matrix Int n m) (hind : b.independent) :
    (Hex.LLLState.ofBasis b hind).Valid := by
  let gs := Hex.GramSchmidt.Int.data b
  constructor
  · intro i j hi hj hji
    simp [Hex.LLLState.ofBasis, Hex.LLLState.ofBasisUnchecked,
      Hex.GramSchmidt.Int.scaledCoeffs]
  · intro i hi
    simpa [Hex.LLLState.ofBasis, Hex.LLLState.ofBasisUnchecked,
      Hex.GramSchmidt.Int.gramDetVec, gs] using
      Hex.GramSchmidt.Int.gramDetVec_eq_gramDet b
        (Hex.GramSchmidt.Int.StepWitness.ofGram b) i (Nat.le_of_lt_succ hi)

/-- Mathlib-side correspondence from the executable LLL state scaled-coefficient
certificate to the rational Gram-Schmidt coefficient relation. -/
theorem lllState_ν_eq_coeffs
    (s : Hex.LLLState n m) (hvalid : s.Valid)
    (i j : Nat) (hi : i < n) (hj : j < n) (hji : j < i) :
    (((s.ν.get ⟨i, hi⟩).get ⟨j, hj⟩ : Int) : Rat) =
      (s.d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ : Rat) *
        (((Hex.GramSchmidt.Int.coeffs s.b).get ⟨i, hi⟩).get ⟨j, hj⟩) := by
  have hν := hvalid.ν_eq i j hi hj hji
  have hd :
      s.d.get ⟨j + 1, Nat.succ_lt_succ hj⟩ =
        Hex.GramSchmidt.Int.gramDet s.b (j + 1)
          (Nat.succ_le_of_lt (Nat.lt_trans hji hi)) :=
    hvalid.d_eq (j + 1) (Nat.succ_lt_succ hj)
  have hscaled :=
    Hex.GramSchmidt.Int.scaledCoeffs_eq s.b i j hi hji
  rw [hν, hd]
  exact hscaled

/-- Integer Lovász check ↔ rational Lovász condition at pair `(k - 1, k)`.

`Hex.lllLoop` dispatches on the integer comparison

```
δ.den * (d[k+1] * d[k-1] + ν[k][k-1]²) ≥ δ.num * d[k]²
```

while `Hex.isLLLReduced` quantifies the rational Lovász condition

```
δ * ‖b*[i]‖² ≤ ‖b*[i+1]‖² + μ[i+1][i]² · ‖b*[i]‖²
```

over every adjacent pair `(i, i+1)`. Under `s.Valid` and `s.b.independent`,
the two formulations agree at pair `(k - 1, k)`: the integer scaled
Gram-Schmidt data carried by `s` faithfully encodes the rational Lovász
predicate at that position. This bridges the loop's executable check to the
specification side of `isLLLReduced` so the loop-invariant proof can read off
"the loop advances ⇒ Lovász holds at this pair." -/
theorem lovasz_check_iff_isLLLReduced_pair
    (s : Hex.LLLState n m) (k : Nat) (hk : k < n) (hk0 : 0 < k)
    (hvalid : s.Valid) (hind : s.b.independent)
    {δ : Rat} (_hδ : (1 : Rat) / 4 < δ) (_hδ' : δ ≤ 1) :
    have hkm1lt : k - 1 < n :=
      Nat.lt_of_le_of_lt (Nat.sub_le k 1) hk
    have hkm1ltN1 : k - 1 < n + 1 :=
      Nat.lt_succ_of_lt (Nat.lt_of_le_of_lt (Nat.sub_le k 1) hk)
    have hkltN1 : k < n + 1 := Nat.lt_succ_of_lt hk
    have hkSuccLt : k + 1 < n + 1 := Nat.succ_lt_succ hk
    Int.ofNat δ.den *
        (Int.ofNat (s.d.get ⟨k + 1, hkSuccLt⟩) *
            Int.ofNat (s.d.get ⟨k - 1, hkm1ltN1⟩) +
          ((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩) ^ 2) ≥
        δ.num * (Int.ofNat (s.d.get ⟨k, hkltN1⟩) ^ 2) ↔
      δ * Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis s.b)
            ⟨k - 1, hkm1lt⟩ ≤
        Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis s.b) ⟨k, hk⟩ +
          (((Hex.GramSchmidt.Int.coeffs s.b).get ⟨k, hk⟩).get
              ⟨k - 1, hkm1lt⟩) *
            (((Hex.GramSchmidt.Int.coeffs s.b).get ⟨k, hk⟩).get
              ⟨k - 1, hkm1lt⟩) *
            Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis s.b)
              ⟨k - 1, hkm1lt⟩ := by
  intro hkm1lt hkm1ltN1 hkltN1 hkSuccLt
  -- Translate the d-field values to Gram determinants.
  have hdk_eq : s.d.get ⟨k, hkltN1⟩ =
      Hex.GramSchmidt.Int.gramDet s.b k (Nat.le_of_lt_succ hkltN1) :=
    hvalid.d_eq k hkltN1
  have hdkPrev_eq : s.d.get ⟨k - 1, hkm1ltN1⟩ =
      Hex.GramSchmidt.Int.gramDet s.b (k - 1) (Nat.le_of_lt_succ hkm1ltN1) :=
    hvalid.d_eq (k - 1) hkm1ltN1
  have hdkNext_eq : s.d.get ⟨k + 1, hkSuccLt⟩ =
      Hex.GramSchmidt.Int.gramDet s.b (k + 1) (Nat.le_of_lt_succ hkSuccLt) :=
    hvalid.d_eq (k + 1) hkSuccLt
  -- ν → coeffs identity at (k, k - 1), normalised so the carried d-index is k.
  have hkm1ltK : k - 1 < k := Nat.sub_lt hk0 Nat.zero_lt_one
  have hsubAdd : k - 1 + 1 = k := Nat.sub_add_cancel hk0
  have hν :
      (((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int) : Rat) =
        (s.d.get ⟨k, hkltN1⟩ : Rat) *
          (((Hex.GramSchmidt.Int.coeffs s.b).get ⟨k, hk⟩).get
            ⟨k - 1, hkm1lt⟩) := by
    have h := lllState_ν_eq_coeffs s hvalid k (k - 1) hk hkm1lt hkm1ltK
    have hidx :
        (⟨k - 1 + 1, Nat.succ_lt_succ hkm1lt⟩ : Fin (n + 1)) =
          ⟨k, hkltN1⟩ :=
      Fin.ext hsubAdd
    rw [hidx] at h
    exact h
  -- Set up the Gram-determinant and basis-norm shorthand.
  set gd_k : Nat :=
    Hex.GramSchmidt.Int.gramDet s.b k (Nat.le_of_lt_succ hkltN1) with hgd_k_def
  set gd_k1 : Nat :=
    Hex.GramSchmidt.Int.gramDet s.b (k + 1) (Nat.le_of_lt_succ hkSuccLt)
      with hgd_k1_def
  set gd_km1 : Nat :=
    Hex.GramSchmidt.Int.gramDet s.b (k - 1) (Nat.le_of_lt_succ hkm1ltN1)
      with hgd_km1_def
  set Nk : Rat :=
    Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis s.b) ⟨k, hk⟩
      with hNk_def
  set Nkm1 : Rat :=
    Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis s.b)
        ⟨k - 1, hkm1lt⟩ with hNkm1_def
  set μ : Rat :=
    ((Hex.GramSchmidt.Int.coeffs s.b).get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩
      with hμ_def
  -- Positivity of the Gram determinants.
  have hgd_k_pos_nat : 0 < gd_k :=
    Hex.GramSchmidt.Int.gramDet_pos s.b hind k
      (Nat.le_of_lt_succ hkltN1) hk0
  have hgd_k1_pos_nat : 0 < gd_k1 :=
    Hex.GramSchmidt.Int.gramDet_pos s.b hind (k + 1)
      (Nat.le_of_lt_succ hkSuccLt) (Nat.succ_pos k)
  have hgd_km1_pos_nat : 0 < gd_km1 := by
    rcases Nat.eq_zero_or_pos (k - 1) with h0 | hpos
    · show 0 < Hex.GramSchmidt.Int.gramDet s.b (k - 1) _
      rw [Hex.GramSchmidt.Int.gramDet_subst_val s.b (k - 1) 0
          (Nat.le_of_lt_succ hkm1ltN1) (Nat.zero_le n) h0,
        Hex.GramSchmidt.Int.gramDet_zero]
      exact Nat.zero_lt_one
    · exact Hex.GramSchmidt.Int.gramDet_pos s.b hind (k - 1)
        (Nat.le_of_lt_succ hkm1ltN1) hpos
  have hgd_k_pos : (0 : Rat) < (gd_k : Rat) := by exact_mod_cast hgd_k_pos_nat
  have hgd_k1_pos : (0 : Rat) < (gd_k1 : Rat) := by exact_mod_cast hgd_k1_pos_nat
  have hgd_km1_pos : (0 : Rat) < (gd_km1 : Rat) := by
    exact_mod_cast hgd_km1_pos_nat
  have hgd_k_ne : (gd_k : Rat) ≠ 0 := ne_of_gt hgd_k_pos
  have hgd_km1_ne : (gd_km1 : Rat) ≠ 0 := ne_of_gt hgd_km1_pos
  have hδden_pos : (0 : Rat) < (δ.den : Rat) := by
    exact_mod_cast δ.den_pos
  have hδden_ne : (δ.den : Rat) ≠ 0 := ne_of_gt hδden_pos
  -- Basis-norm identities.
  have hNk_mul : (gd_k : Rat) * Nk = (gd_k1 : Rat) := by
    have hbn := Hex.GramSchmidt.Int.basis_normSq s.b hind k hk
    have hNk_val : Nk = (gd_k1 : Rat) / (gd_k : Rat) := by
      show Hex.Vector.normSq ((Hex.GramSchmidt.Int.basis s.b).row ⟨k, hk⟩) = _
      exact hbn
    rw [hNk_val, mul_div_cancel₀ _ hgd_k_ne]
  have hNkm1_mul : (gd_km1 : Rat) * Nkm1 = (gd_k : Rat) := by
    have hbn := Hex.GramSchmidt.Int.basis_normSq s.b hind (k - 1) hkm1lt
    have hNkm1_val :
        Nkm1 = (Hex.GramSchmidt.Int.gramDet s.b (k - 1 + 1)
            (Nat.succ_le_of_lt hkm1lt) : Rat) / (gd_km1 : Rat) := by
      show Hex.Vector.normSq ((Hex.GramSchmidt.Int.basis s.b).row ⟨k - 1, hkm1lt⟩) = _
      exact hbn
    have hgd_eq :
        Hex.GramSchmidt.Int.gramDet s.b (k - 1 + 1)
            (Nat.succ_le_of_lt hkm1lt) = gd_k :=
      Hex.GramSchmidt.Int.gramDet_subst_val s.b (k - 1 + 1) k
        (Nat.succ_le_of_lt hkm1lt) (Nat.le_of_lt_succ hkltN1) hsubAdd
    rw [hgd_eq] at hNkm1_val
    rw [hNkm1_val, mul_div_cancel₀ _ hgd_km1_ne]
  -- δ * δ.den = δ.num (over Rat).
  have hδmul : δ * (δ.den : Rat) = (δ.num : Rat) := Rat.mul_den_eq_num δ
  -- Cast B = ν[k][k-1] = gd_k * μ (over Rat).
  have hB_cast :
      (((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int) : Rat) =
        (gd_k : Rat) * μ := by
    rw [hν, hdk_eq]
  have hB_sq :
      ((((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int)) ^ 2 : Rat) =
        (gd_k : Rat) ^ 2 * μ ^ 2 := by
    have hsq : (((((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int)) : Rat)) ^ 2 =
        ((gd_k : Rat) * μ) ^ 2 := by rw [hB_cast]
    rw [show ((((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int)) ^ 2 : Rat) =
          (((((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩ : Int)) : Rat)) ^ 2 from by
        rfl, hsq]; ring
  -- Convert the integer inequality to an equivalent Rat inequality with all
  -- `Int.ofNat`/`Int → Rat` casts normalised to direct `Nat → Rat` casts.
  have hcast_iff :
      (Int.ofNat δ.den *
          (Int.ofNat (s.d.get ⟨k + 1, hkSuccLt⟩) *
              Int.ofNat (s.d.get ⟨k - 1, hkm1ltN1⟩) +
            ((s.ν.get ⟨k, hk⟩).get ⟨k - 1, hkm1lt⟩) ^ 2) ≥
        δ.num * (Int.ofNat (s.d.get ⟨k, hkltN1⟩) ^ 2)) ↔
      ((δ.den : Rat) *
          ((gd_k1 : Rat) * (gd_km1 : Rat) +
            (gd_k : Rat) ^ 2 * μ ^ 2) ≥
        (δ.num : Rat) * (gd_k : Rat) ^ 2) := by
    rw [ge_iff_le, ge_iff_le, ← @Int.cast_le ℚ]
    rw [hdk_eq, hdkPrev_eq, hdkNext_eq]
    push_cast
    rw [hB_sq]
    simp only [Int.ofNat_eq_natCast, Int.cast_natCast]
  rw [hcast_iff]
  -- Define the positive multiplier and the identity.
  set P : Rat := (δ.den : Rat) * (gd_k : Rat) * (gd_km1 : Rat) with hP_def
  have hP_pos : 0 < P := by
    have : 0 < (δ.den : Rat) * (gd_k : Rat) := mul_pos hδden_pos hgd_k_pos
    exact mul_pos this hgd_km1_pos
  -- The key algebraic identity:
  --   δ.den * (gd_k1 * gd_km1 + gd_k^2 * μ^2) - δ.num * gd_k^2
  -- = P * ((Nk + Nkm1 * μ^2) - δ * Nkm1)
  -- proved by substituting gd_k1 = gd_k * Nk, gd_k = gd_km1 * Nkm1, and
  -- δ.num = δ * δ.den, then ring.
  have hidentity :
      (δ.den : Rat) *
          ((gd_k1 : Rat) * (gd_km1 : Rat) + (gd_k : Rat) ^ 2 * μ ^ 2) -
        (δ.num : Rat) * (gd_k : Rat) ^ 2 =
      P * ((Nk + Nkm1 * μ * μ) - δ * Nkm1) := by
    have hμ_sq : μ ^ 2 = μ * μ := sq μ
    rw [hP_def, ← hNk_mul, ← hNkm1_mul, ← hδmul, hμ_sq]
    ring
  -- Convert both sides to "≤ 0" form and use the identity.
  constructor
  · intro hint
    have hLHS_ge :
        0 ≤ (δ.den : Rat) *
              ((gd_k1 : Rat) * (gd_km1 : Rat) + (gd_k : Rat) ^ 2 * μ ^ 2) -
            (δ.num : Rat) * (gd_k : Rat) ^ 2 := by linarith
    rw [hidentity] at hLHS_ge
    have hdiff_nn :
        0 ≤ (Nk + Nkm1 * μ * μ) - δ * Nkm1 :=
      (mul_nonneg_iff_of_pos_left hP_pos).mp hLHS_ge
    linarith
  · intro hrat
    have hdiff_nn : 0 ≤ (Nk + Nkm1 * μ * μ) - δ * Nkm1 := by linarith
    have hLHS_ge :
        0 ≤ (δ.den : Rat) *
              ((gd_k1 : Rat) * (gd_km1 : Rat) + (gd_k : Rat) ^ 2 * μ ^ 2) -
            (δ.num : Rat) * (gd_k : Rat) ^ 2 := by
      rw [hidentity]
      exact mul_nonneg (le_of_lt hP_pos) hdiff_nn
    linarith

/-- The Mathlib `Submodule ℤ` generated by the rows of an executable integer
matrix. -/
@[expose]
def latticeSubmodule (b : Hex.Matrix Int n m) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))

theorem mem_latticeSubmodule_iff (b : Hex.Matrix Int n m) (v : Vector Int m) :
    HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b ↔ Hex.Matrix.memLattice b v := by
  unfold latticeSubmodule Hex.Matrix.memLattice
  rw [Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨HexMatrixMathlib.vectorEquiv.symm c,
      HexMatrixMathlib.vectorEquiv.injective ?_⟩
    rw [HexMatrixMathlib.vectorEquiv_rowCombination,
      Fintype.linearCombination_apply, Equiv.apply_symm_apply]
    refine (Finset.sum_congr rfl fun i _ => ?_).trans hc
    rw [HexMatrixMathlib.matrixEquiv_row]
  · rintro ⟨c, hc⟩
    refine ⟨HexMatrixMathlib.vectorEquiv c, ?_⟩
    have hr := HexMatrixMathlib.vectorEquiv_rowCombination b c
    rw [hc, Fintype.linearCombination_apply] at hr
    rw [hr]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [HexMatrixMathlib.matrixEquiv_row]

theorem memLattice_iff_mem_latticeSubmodule (b : Hex.Matrix Int n m) (v : Vector Int m) :
    Hex.Matrix.memLattice b v ↔ HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b :=
  (mem_latticeSubmodule_iff b v).symm

theorem row_mem_latticeSubmodule (b : Hex.Matrix Int n m) (i : Fin n) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ latticeSubmodule b := by
  exact Submodule.subset_span (Set.mem_range_self i)

/-- The submodule generated by rows whose indices are strictly below `t`. -/
@[expose]
def prefixSubmodule (b : Hex.Matrix Int n m) (t : Nat) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : {i : Fin n // i.val < t} =>
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i.1))

theorem row_mem_prefixSubmodule (b : Hex.Matrix Int n m) (t : Nat)
    (i : Fin n) (hi : i.val < t) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ prefixSubmodule b t := by
  exact Submodule.subset_span ⟨⟨i, hi⟩, rfl⟩

theorem prefixSubmodule_le_latticeSubmodule (b : Hex.Matrix Int n m) (t : Nat) :
    prefixSubmodule b t ≤ latticeSubmodule b := by
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨i, rfl⟩
  exact row_mem_latticeSubmodule b i.1

theorem rowCombination_mem_prefixSubmodule (b : Hex.Matrix Int n m)
    (c : Fin n → ℤ) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c i = 0) :
    (Fintype.linearCombination ℤ
        (fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))) c ∈
      prefixSubmodule b t := by
  rw [Fintype.linearCombination_apply]
  refine Submodule.sum_mem _ ?_
  intro i _hi
  by_cases hit : i.val < t
  · exact Submodule.smul_mem _ (c i) (row_mem_prefixSubmodule b t i hit)
  · have hci : c i = 0 := hc i (Nat.le_of_not_gt hit)
    simp [hci]

theorem rowCombination_mem_prefixSubmodule_of_vector (b : Hex.Matrix Int n m)
    (c : Vector Int n) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c[i] = 0) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.rowCombination b c) ∈ prefixSubmodule b t := by
  rw [HexMatrixMathlib.vectorEquiv_rowCombination]
  exact rowCombination_mem_prefixSubmodule b (HexMatrixMathlib.vectorEquiv c) t
    (fun i hi => by simpa [HexMatrixMathlib.vectorEquiv] using hc i hi)

theorem prefixRowCombination_memLattice (b : Hex.Matrix Int n m)
    (c : Vector Int n) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c[i] = 0) :
    Hex.Matrix.memLattice b (Hex.Matrix.rowCombination b c) := by
  apply (mem_latticeSubmodule_iff b _).mp
  simpa using
    prefixSubmodule_le_latticeSubmodule b t
      (rowCombination_mem_prefixSubmodule_of_vector b c t hc)

/-- View an executable integer row as a vector in Mathlib's standard Euclidean
space on `Fin m`. -/
@[expose]
def intRowToEuclidean (row : Vector Int m) : EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun j : Fin m => (row[j] : ℝ))

/-- View a Mathlib-side integer lattice vector in Mathlib's standard Euclidean
space on `Fin m`. -/
@[expose]
def intVectorToEuclidean (x : Fin m → ℤ) : EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun j : Fin m => (x j : ℝ))

private theorem foldl_finRange_eq_sum {R : Type*} [AddCommMonoid R] {n : Nat}
    (f : Fin n → R) :
    (List.finRange n).foldl (fun acc i => acc + f i) 0 = ∑ i, f i := by
  rw [← List.foldl_map, ← List.sum_eq_foldl,
    ← List.sum_toFinset f (List.nodup_finRange n), List.toFinset_finRange]

/-- The Euclidean squared norm of an integer row embedded into
`EuclideanSpace ℝ (Fin m)` equals the real cast of the executable integer
squared norm. -/
theorem norm_sq_intRowToEuclidean (row : Vector Int m) :
    ‖intRowToEuclidean row‖ ^ 2 = ((Hex.Vector.normSq row : Int) : ℝ) := by
  rw [EuclideanSpace.real_norm_sq_eq]
  simp only [intRowToEuclidean, PiLp.toLp_apply]
  unfold Hex.Vector.normSq Hex.Vector.dotProduct
  rw [foldl_finRange_eq_sum]
  push_cast
  refine Finset.sum_congr rfl ?_
  intro i _
  ring

/-- The Euclidean squared norm of a lattice vector embedded into
`EuclideanSpace ℝ (Fin m)` equals the real cast of the executable integer
squared norm of its `Vector` preimage. -/
theorem norm_sq_intVectorToEuclidean (x : Fin m → ℤ) :
    ‖intVectorToEuclidean x‖ ^ 2 =
      ((Hex.Vector.normSq (HexMatrixMathlib.vectorEquiv.symm x) : Int) : ℝ) := by
  have heq :
      intVectorToEuclidean x =
        intRowToEuclidean (HexMatrixMathlib.vectorEquiv.symm x) := by
    unfold intVectorToEuclidean intRowToEuclidean HexMatrixMathlib.vectorEquiv
    ext j
    simp [Vector.getElem_ofFn]
  rw [heq, norm_sq_intRowToEuclidean]

/-- Mathlib-Euclidean-norm formulation of the LLL short-vector guarantee for
an already `(δ, η)`-LLL-reduced executable basis.

The input vector is assumed to lie in the Mathlib `latticeSubmodule`.  The
proof route converts that hypothesis back through `mem_latticeSubmodule_iff`,
applies the executable `Hex.short_vector_bound_of_size_bound` for the
rational squared-norm inequality, then transports both sides through the
concrete Euclidean norm coercions above.

Consumed downstream at `η = 11/20` for the public `Hex.lll` headline
(`α = 1/(δ − 121/400)`, precondition `121/400 < δ`); also at `η = 1/2` for
the native `Hex.lllNative` classical statement (`α = 1/(δ − 1/4)`,
precondition `1/4 < δ`). -/
theorem reduced_first_row_norm_sq_le_of_mem_latticeSubmodule
    (b : Hex.Matrix Int n m) (δ η : Rat)
    (hη : (1 : Rat) / 2 ≤ η) (hδη : η * η < δ) (hδ' : δ ≤ 1) (hn : 1 ≤ n)
    (hli : Hex.Matrix.independent b) (hred : Hex.isLLLReduced b δ η)
    (x : Fin m → ℤ) (hx : x ∈ latticeSubmodule b) (hx0 : x ≠ 0) :
    ‖intRowToEuclidean (Hex.Matrix.row b ⟨0, Nat.lt_of_lt_of_le Nat.zero_lt_one hn⟩)‖ ^ 2 ≤
      (((1 / (δ - η * η)) ^ (n - 1) : Rat) : ℝ) *
        ‖intVectorToEuclidean x‖ ^ 2 := by
  let v : Vector Int m := HexMatrixMathlib.vectorEquiv.symm x
  have hxExec : Hex.Matrix.memLattice b v := by
    have hx' : HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b := by
      simpa [v] using hx
    exact (mem_latticeSubmodule_iff b v).mp hx'
  have hx0Exec : v ≠ 0 := by
    intro hv
    apply hx0
    have hv' : HexMatrixMathlib.vectorEquiv v = 0 := by
      ext j
      simp [hv]
    simpa [v] using hv'
  have hRat := Hex.short_vector_bound_of_size_bound b hli hred hη hδη hδ' hn
    hxExec hx0Exec
  have hReal := (Rat.cast_le (K := ℝ)).mpr hRat
  rw [norm_sq_intRowToEuclidean, norm_sq_intVectorToEuclidean]
  simp only [Rat.cast_mul, Rat.cast_intCast] at hReal
  exact hReal

/-! ### Soundness of the integer reducedness checker

`Hex.lllReducedInt b δ η` accepts iff three integer-only inequalities hold over
`Hex.GramSchmidt.Int.data b`. This section bridges those integer inequalities
to the rational predicate `Hex.isLLLReduced b δ η` and to `b.independent`, the
last theorem (`Hex.lllReducedInt_sound`) being the D2 deliverable used by the
combined `certCheck_sound` of `hex-lll` §"Certified external dispatch". -/

/-- Independence from the executable checker's `d`-positivity pass.

The integer `d`-vector `(GramSchmidt.Int.data b).d = gramDetVec b` agrees with
`gramDet b` slot-by-slot (`gramDetVec_eq_gramDet` with `StepWitness.ofGram`),
so each positive `d[k+1]` is exactly the `gramDet`-positivity defining
`b.independent`. -/
private theorem independent_of_dPos
    {n m : Nat} (b : Hex.Matrix Int n m)
    (hdPos : ∀ k : Fin n,
      0 < (Hex.GramSchmidt.Int.data b).d.get
        ⟨k.val + 1, Nat.succ_lt_succ k.isLt⟩) :
    Hex.Matrix.independent b := by
  intro k
  have h := hdPos k
  have heq :
      (Hex.GramSchmidt.Int.data b).d.get ⟨k.val + 1, Nat.succ_lt_succ k.isLt⟩ =
        Hex.GramSchmidt.Int.gramDet b (k.val + 1) (Nat.succ_le_of_lt k.isLt) := by
    have hbridge :=
      Hex.GramSchmidt.Int.gramDetVec_eq_gramDet b
        (Hex.GramSchmidt.Int.StepWitness.ofGram b)
        (k.val + 1) (Nat.succ_le_of_lt k.isLt)
    simpa [Hex.GramSchmidt.Int.gramDetVec] using hbridge
  show 0 < Hex.GramSchmidt.Int.gramDet b (k.val + 1) (Nat.succ_le_of_lt k.isLt)
  rw [← heq]
  exact h

/-- Size-reduced contribution: from one integer `|ν| · η.den ≤ η.num · d[j+1]`
inequality plus `0 < d[j+1]`, derive `μ² ≤ η²` at the same `(i, j)` slot.

The bridge is `scaledCoeffs_eq`, which equates `(ν[i][j] : Rat)` with
`d[j+1] · μ[i][j]`. Once `d[j+1] > 0` and `η.den > 0` are pinned, division by
the positive product `d[j+1] · η.den` turns the integer inequality into
`|μ| ≤ η`, hence (since `η ≥ 0` follows from the same inequality) `μ² ≤ η²`. -/
private theorem sizeSq_of_intCheck
    {n m : Nat} (b : Hex.Matrix Int n m) (_δ η : Rat) {i j : Nat}
    (hi : i < n) (hji : j < i)
    (hd_pos : 0 < (Hex.GramSchmidt.Int.data b).d.get
      ⟨j + 1, Nat.succ_lt_succ (Nat.lt_trans hji hi)⟩)
    (hint :
      ((η.den : Int) *
          ((((Hex.GramSchmidt.Int.data b).ν.get ⟨i, hi⟩).get
              ⟨j, Nat.lt_trans hji hi⟩).natAbs : Int)) ≤
        η.num *
          ((Hex.GramSchmidt.Int.data b).d.get
            ⟨j + 1, Nat.succ_lt_succ (Nat.lt_trans hji hi)⟩ : Int)) :
    (((Hex.GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get
        ⟨j, Nat.lt_trans hji hi⟩) *
      (((Hex.GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get
        ⟨j, Nat.lt_trans hji hi⟩) ≤ η * η := by
  -- Names for the integer slots.
  set νij : Int := ((Hex.GramSchmidt.Int.data b).ν.get ⟨i, hi⟩).get
      ⟨j, Nat.lt_trans hji hi⟩ with hνij_def
  set dj1 : Nat := (Hex.GramSchmidt.Int.data b).d.get
      ⟨j + 1, Nat.succ_lt_succ (Nat.lt_trans hji hi)⟩ with hdj1_def
  set μ : Rat := ((Hex.GramSchmidt.Int.coeffs b).get ⟨i, hi⟩).get
      ⟨j, Nat.lt_trans hji hi⟩ with hμ_def
  -- Bridge ν[i][j] ↔ d[j+1] · μ via scaledCoeffs_eq.
  have hbridge :
      (νij : Rat) = (dj1 : Rat) * μ := by
    have h := Hex.GramSchmidt.Int.scaledCoeffs_eq b i j hi hji
    -- h equates the GS-entry of scaledCoeffs to gramDet·coeffs-entry.
    -- (Hex.GramSchmidt.Int.data b).ν = Hex.GramSchmidt.Int.scaledCoeffs b
    -- (Hex.GramSchmidt.Int.data b).d.get ⟨j+1, _⟩ = gramDet b (j+1).
    have hScaled :
        (Hex.GramSchmidt.entry (Hex.GramSchmidt.Int.scaledCoeffs b)
            ⟨i, hi⟩ ⟨j, Nat.lt_trans hji hi⟩ : Int) = νij := by
      rfl
    have hdEq :
        (dj1 : Nat) = Hex.GramSchmidt.Int.gramDet b (j + 1)
          (Nat.succ_le_of_lt (Nat.lt_trans hji hi)) := by
      have hbridge_d :=
        Hex.GramSchmidt.Int.gramDetVec_eq_gramDet b
          (Hex.GramSchmidt.Int.StepWitness.ofGram b)
          (j + 1) (Nat.succ_le_of_lt (Nat.lt_trans hji hi))
      simpa [Hex.GramSchmidt.Int.gramDetVec, hdj1_def] using hbridge_d
    have hμEq :
        Hex.GramSchmidt.entry (Hex.GramSchmidt.Int.coeffs b) ⟨i, hi⟩
            ⟨j, Nat.lt_trans hji hi⟩ = μ := by
      rfl
    rw [hScaled] at h
    rw [hμEq] at h
    rw [hdEq]
    exact h
  -- Positivity casts.
  have hdj1_pos : (0 : Rat) < (dj1 : Rat) := by exact_mod_cast hd_pos
  have hdj1_ne : (dj1 : Rat) ≠ 0 := ne_of_gt hdj1_pos
  have hηden_pos : (0 : Rat) < (η.den : Rat) := by exact_mod_cast η.den_pos
  have hηden_ne : (η.den : Rat) ≠ 0 := ne_of_gt hηden_pos
  -- Cast the integer inequality to Rat.
  have hcast : (η.den : Rat) * (νij.natAbs : Rat) ≤ (η.num : Rat) * (dj1 : Rat) := by
    have hint' : (((η.den : Int) * (νij.natAbs : Int) : Int) : Rat) ≤
        ((η.num * (dj1 : Int) : Int) : Rat) := by exact_mod_cast hint
    simpa [Int.cast_mul, Int.cast_natCast] using hint'
  -- η.num ≥ 0 follows: LHS = η.den · |νij| ≥ 0, so η.num · dj1 ≥ 0, then ÷ dj1 > 0.
  have hnumNonneg : (0 : Rat) ≤ (η.num : Rat) := by
    have hLHS_nn : (0 : Rat) ≤ (η.den : Rat) * (νij.natAbs : Rat) := by
      have h1 : (0 : Rat) ≤ (η.den : Rat) := le_of_lt hηden_pos
      have h2 : (0 : Rat) ≤ (νij.natAbs : Rat) := Nat.cast_nonneg _
      exact mul_nonneg h1 h2
    have hRHS_nn : (0 : Rat) ≤ (η.num : Rat) * (dj1 : Rat) :=
      le_trans hLHS_nn hcast
    -- Divide by dj1 > 0.
    have := (mul_nonneg_iff_of_pos_right hdj1_pos).mp hRHS_nn
    exact this
  -- Therefore η ≥ 0.
  have hη_nonneg : (0 : Rat) ≤ η := by
    have hη_eq : η = (η.num : Rat) / (η.den : Rat) := (Rat.num_div_den η).symm
    rw [hη_eq]
    exact div_nonneg hnumNonneg (le_of_lt hηden_pos)
  -- The absolute value of μ.
  -- Rat: |μ| = |νij| / dj1.
  have habsμ_eq : |μ| = (νij.natAbs : Rat) / (dj1 : Rat) := by
    have hμ_val : μ = (νij : Rat) / (dj1 : Rat) := by
      rw [eq_div_iff hdj1_ne, mul_comm]
      exact hbridge.symm
    rw [hμ_val]
    rw [abs_div]
    have habs_dj1 : |(dj1 : Rat)| = (dj1 : Rat) := abs_of_pos hdj1_pos
    rw [habs_dj1]
    have habs_νij : |(νij : Rat)| = (νij.natAbs : Rat) := by
      rw [Nat.cast_natAbs]
      exact (Int.cast_abs).symm
    rw [habs_νij]
  -- |μ| ≤ η: divide the integer inequality by (η.den · dj1) > 0.
  have habsμ_le_η : |μ| ≤ η := by
    rw [habsμ_eq]
    have hη_eq : η = (η.num : Rat) / (η.den : Rat) := (Rat.num_div_den η).symm
    rw [hη_eq]
    -- We want (|νij| : Rat) / dj1 ≤ η.num / η.den.
    -- Equivalent to: |νij| · η.den ≤ η.num · dj1 (LHS, RHS positive).
    rw [div_le_div_iff₀ hdj1_pos hηden_pos]
    have hswap : (νij.natAbs : Rat) * (η.den : Rat) =
        (η.den : Rat) * (νij.natAbs : Rat) := by ring
    rw [hswap]
    exact hcast
  -- Therefore μ² ≤ η².
  have h0_le_absμ : 0 ≤ |μ| := abs_nonneg μ
  have hsq1 : |μ| * |μ| ≤ η * |μ| := by
    exact mul_le_mul_of_nonneg_right habsμ_le_η h0_le_absμ
  have hsq2 : η * |μ| ≤ η * η := by
    exact mul_le_mul_of_nonneg_left habsμ_le_η hη_nonneg
  have hμsq_eq : |μ| * |μ| = μ * μ := by
    rw [abs_mul_abs_self]
  rw [← hμsq_eq]
  exact le_trans hsq1 hsq2

/-- Lovász contribution: from one integer Lovász inequality at slot `i`
plus positivity of the three involved `d` entries, derive the rational
Lovász condition at the same slot.

Same algebraic identity as `lovasz_check_iff_isLLLReduced_pair`, but stated
directly on `(GramSchmidt.Int.data b).d / ν` rather than going through an
`LLLState`. Bridges: `gramDetVec_eq_gramDet`, `scaledCoeffs_eq`, and
`basis_normSq`. -/
private theorem lovasz_of_intCheck
    {n m : Nat} (b : Hex.Matrix Int n m) (δ _η : Rat) {i : Nat}
    (hi : i + 1 < n) (hindep : Hex.Matrix.independent b)
    (hint :
      (δ.den : Int) *
          (((Hex.GramSchmidt.Int.data b).d.get
              ⟨i + 2, Nat.succ_lt_succ hi⟩ : Int) *
              ((Hex.GramSchmidt.Int.data b).d.get
                ⟨i, Nat.lt_succ_of_lt
                  (Nat.lt_trans (Nat.lt_succ_self i) hi)⟩ : Int) +
            (((Hex.GramSchmidt.Int.data b).ν.get ⟨i + 1, hi⟩).get
              ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩) ^ 2) ≥
        δ.num *
          ((Hex.GramSchmidt.Int.data b).d.get
            ⟨i + 1, Nat.succ_lt_succ
              (Nat.lt_trans (Nat.lt_succ_self i) hi)⟩ : Int) ^ 2) :
    δ * Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis b)
        ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩ ≤
      Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis b) ⟨i + 1, hi⟩ +
        (((Hex.GramSchmidt.Int.coeffs b).get ⟨i + 1, hi⟩).get
            ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩) *
          (((Hex.GramSchmidt.Int.coeffs b).get ⟨i + 1, hi⟩).get
            ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩) *
          Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis b)
            ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩ := by
  have hi_lt : i < n := Nat.lt_trans (Nat.lt_succ_self i) hi
  have hi1_lt : i + 1 < n := hi
  set iFin : Fin n := ⟨i, hi_lt⟩ with hiFin_def
  set ip1Fin : Fin n := ⟨i + 1, hi⟩ with hip1Fin_def
  have hi0_le : 0 ≤ i := Nat.zero_le _
  -- Bridge `data.d.get ⟨k, ...⟩ = gramDet b k _`.
  have hd_bridge :
      ∀ k (hk : k ≤ n),
        (Hex.GramSchmidt.Int.data b).d.get ⟨k, Nat.lt_succ_of_le hk⟩ =
          Hex.GramSchmidt.Int.gramDet b k hk := by
    intro k hk
    have hbr :=
      Hex.GramSchmidt.Int.gramDetVec_eq_gramDet b
        (Hex.GramSchmidt.Int.StepWitness.ofGram b) k hk
    simpa [Hex.GramSchmidt.Int.gramDetVec] using hbr
  set gd_i : Nat :=
    Hex.GramSchmidt.Int.gramDet b i (Nat.le_of_lt hi_lt) with hgd_i_def
  set gd_i1 : Nat :=
    Hex.GramSchmidt.Int.gramDet b (i + 1)
      (Nat.succ_le_of_lt hi_lt) with hgd_i1_def
  set gd_i2 : Nat :=
    Hex.GramSchmidt.Int.gramDet b (i + 2)
      (Nat.succ_le_of_lt hi1_lt) with hgd_i2_def
  have hdi_eq : (Hex.GramSchmidt.Int.data b).d.get
      ⟨i, Nat.lt_succ_of_lt hi_lt⟩ = gd_i :=
    hd_bridge i (Nat.le_of_lt hi_lt)
  have hdi1_eq : (Hex.GramSchmidt.Int.data b).d.get
      ⟨i + 1, Nat.succ_lt_succ hi_lt⟩ = gd_i1 :=
    hd_bridge (i + 1) (Nat.succ_le_of_lt hi_lt)
  have hdi2_eq : (Hex.GramSchmidt.Int.data b).d.get
      ⟨i + 2, Nat.succ_lt_succ hi⟩ = gd_i2 :=
    hd_bridge (i + 2) (Nat.succ_le_of_lt hi1_lt)
  -- Positivity of the three gd values.
  have hgd_i1_pos : 0 < gd_i1 :=
    Hex.GramSchmidt.Int.gramDet_pos b hindep (i + 1)
      (Nat.succ_le_of_lt hi_lt) (Nat.succ_pos i)
  have hgd_i2_pos : 0 < gd_i2 :=
    Hex.GramSchmidt.Int.gramDet_pos b hindep (i + 2)
      (Nat.succ_le_of_lt hi1_lt) (Nat.succ_pos (i + 1))
  have hgd_i_pos : 0 < gd_i := by
    rcases Nat.eq_zero_or_pos i with h0 | hpos
    · show 0 < Hex.GramSchmidt.Int.gramDet b i _
      rw [Hex.GramSchmidt.Int.gramDet_subst_val b i 0
          (Nat.le_of_lt hi_lt) (Nat.zero_le n) h0,
        Hex.GramSchmidt.Int.gramDet_zero]
      exact Nat.zero_lt_one
    · exact Hex.GramSchmidt.Int.gramDet_pos b hindep i
        (Nat.le_of_lt hi_lt) hpos
  have hgd_i_posR : (0 : Rat) < (gd_i : Rat) := by exact_mod_cast hgd_i_pos
  have hgd_i1_posR : (0 : Rat) < (gd_i1 : Rat) := by exact_mod_cast hgd_i1_pos
  have hgd_i2_posR : (0 : Rat) < (gd_i2 : Rat) := by exact_mod_cast hgd_i2_pos
  have hgd_i_ne : (gd_i : Rat) ≠ 0 := ne_of_gt hgd_i_posR
  have hgd_i1_ne : (gd_i1 : Rat) ≠ 0 := ne_of_gt hgd_i1_posR
  have hδden_pos : (0 : Rat) < (δ.den : Rat) := by exact_mod_cast δ.den_pos
  -- Basis norm identities.
  set Ni : Rat := Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis b) iFin
    with hNi_def
  set Ni1 : Rat := Hex.LLLCore.basisNormSq (Hex.GramSchmidt.Int.basis b) ip1Fin
    with hNi1_def
  have hNi_mul : (gd_i : Rat) * Ni = (gd_i1 : Rat) := by
    have hbn := Hex.GramSchmidt.Int.basis_normSq b hindep i hi_lt
    have hNi_val : Ni = (gd_i1 : Rat) / (gd_i : Rat) := by
      show Hex.Vector.normSq ((Hex.GramSchmidt.Int.basis b).row ⟨i, hi_lt⟩) = _
      exact hbn
    rw [hNi_val, mul_div_cancel₀ _ hgd_i_ne]
  have hNi1_mul : (gd_i1 : Rat) * Ni1 = (gd_i2 : Rat) := by
    have hbn := Hex.GramSchmidt.Int.basis_normSq b hindep (i + 1) hi1_lt
    have hNi1_val : Ni1 = (gd_i2 : Rat) / (gd_i1 : Rat) := by
      show Hex.Vector.normSq ((Hex.GramSchmidt.Int.basis b).row ⟨i + 1, hi1_lt⟩) = _
      exact hbn
    rw [hNi1_val, mul_div_cancel₀ _ hgd_i1_ne]
  -- ν[i+1][i] = gd_i1 · μ via scaledCoeffs_eq.
  set νB : Int := ((Hex.GramSchmidt.Int.data b).ν.get ip1Fin).get ⟨i, hi_lt⟩
    with hνB_def
  set μ : Rat := ((Hex.GramSchmidt.Int.coeffs b).get ip1Fin).get ⟨i, hi_lt⟩
    with hμ_def
  have hμ_bridge : (νB : Rat) = (gd_i1 : Rat) * μ := by
    have h := Hex.GramSchmidt.Int.scaledCoeffs_eq b (i + 1) i hi1_lt
      (Nat.lt_succ_self i)
    have hScaled :
        (Hex.GramSchmidt.entry (Hex.GramSchmidt.Int.scaledCoeffs b)
            ip1Fin ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi1_lt⟩ : Int) = νB := by
      rfl
    have hμEq :
        Hex.GramSchmidt.entry (Hex.GramSchmidt.Int.coeffs b) ip1Fin
            ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi1_lt⟩ = μ := by
      rfl
    rw [hScaled] at h
    rw [hμEq] at h
    -- Need to rewrite the gd_i1 cast.
    have hgdEq : Hex.GramSchmidt.Int.gramDet b (i + 1)
        (Nat.succ_le_of_lt (Nat.lt_trans (Nat.lt_succ_self i) hi1_lt)) =
        gd_i1 := by rfl
    rw [hgdEq] at h
    exact h
  -- Square form.
  have hνB_sq : ((νB : Int) ^ 2 : Rat) = (gd_i1 : Rat) ^ 2 * μ ^ 2 := by
    have hsq : ((νB : Rat)) ^ 2 = ((gd_i1 : Rat) * μ) ^ 2 := by rw [hμ_bridge]
    rw [show ((νB : Int) ^ 2 : Rat) = ((νB : Rat)) ^ 2 from rfl,
      hsq]; ring
  -- δ.den · δ = δ.num.
  have hδmul : δ * (δ.den : Rat) = (δ.num : Rat) := Rat.mul_den_eq_num δ
  -- Convert the integer hypothesis to a Rat inequality.
  have hcast_iff :
      ((δ.den : Rat) *
          ((gd_i2 : Rat) * (gd_i : Rat) + (gd_i1 : Rat) ^ 2 * μ ^ 2) ≥
        (δ.num : Rat) * (gd_i1 : Rat) ^ 2) := by
    have hcastR : ((δ.den : Int) *
        (((Hex.GramSchmidt.Int.data b).d.get ⟨i + 2, Nat.succ_lt_succ hi⟩ : Int) *
            ((Hex.GramSchmidt.Int.data b).d.get
                ⟨i, Nat.lt_succ_of_lt hi_lt⟩ : Int) +
          (((Hex.GramSchmidt.Int.data b).ν.get ip1Fin).get ⟨i, hi_lt⟩) ^ 2) : Rat) ≥
        ((δ.num *
          ((Hex.GramSchmidt.Int.data b).d.get
            ⟨i + 1, Nat.succ_lt_succ hi_lt⟩ : Int) ^ 2 : Int) : Rat) := by
      exact_mod_cast hint
    -- Substitute the d-bridges (Nat-side) on both sides.
    rw [hdi_eq, hdi1_eq, hdi2_eq] at hcastR
    rw [hνB_sq] at hcastR
    push_cast at hcastR
    exact hcastR
  -- The key algebraic identity:
  --   δ.den · (gd_i2 · gd_i + gd_i1² · μ²) - δ.num · gd_i1² =
  --   P · (Ni1 + Ni · μ² - δ · Ni)
  -- where P = δ.den · gd_i · gd_i1.
  set P : Rat := (δ.den : Rat) * (gd_i : Rat) * (gd_i1 : Rat) with hP_def
  have hP_pos : 0 < P := by
    have h1 : 0 < (δ.den : Rat) * (gd_i : Rat) := mul_pos hδden_pos hgd_i_posR
    exact mul_pos h1 hgd_i1_posR
  have hidentity :
      (δ.den : Rat) *
          ((gd_i2 : Rat) * (gd_i : Rat) + (gd_i1 : Rat) ^ 2 * μ ^ 2) -
        (δ.num : Rat) * (gd_i1 : Rat) ^ 2 =
      P * ((Ni1 + Ni * μ * μ) - δ * Ni) := by
    have hμ_sq : μ ^ 2 = μ * μ := sq μ
    rw [hP_def, ← hNi1_mul, ← hNi_mul, ← hδmul, hμ_sq]
    ring
  -- From the cast inequality and the identity, derive the rational Lovász.
  have hLHS_ge :
      0 ≤ (δ.den : Rat) *
              ((gd_i2 : Rat) * (gd_i : Rat) + (gd_i1 : Rat) ^ 2 * μ ^ 2) -
            (δ.num : Rat) * (gd_i1 : Rat) ^ 2 := by linarith
  rw [hidentity] at hLHS_ge
  have hdiff_nn : 0 ≤ (Ni1 + Ni * μ * μ) - δ * Ni :=
    (mul_nonneg_iff_of_pos_left hP_pos).mp hLHS_ge
  linarith

/-- D2 soundness theorem: the executable integer reducedness checker entails
both `b.independent` and the rational `isLLLReduced b δ η` predicate.

This is one of the two soundness ingredients feeding the combined
`certCheck_sound` of `hex-lll` §"Certified external dispatch". The
companion same-lattice piece is `Hex.Matrix.sameLatticeCert_sound`. -/
theorem lllReducedInt_sound (b : Hex.Matrix Int n m) (δ η : Rat) :
    Hex.lllReducedInt b δ η = true →
      Hex.isLLLReduced b δ η ∧ Hex.Matrix.independent b := by
  intro hcheck
  -- Unfold the three pieces of the Bool check.
  unfold Hex.lllReducedInt at hcheck
  simp only [Bool.and_eq_true, List.all_eq_true, List.mem_finRange,
    decide_eq_true_eq, forall_true_left] at hcheck
  obtain ⟨⟨hdPos, hsize⟩, hlovasz_raw⟩ := hcheck
  -- Independence.
  have hindep : Hex.Matrix.independent b := independent_of_dPos b hdPos
  -- Repackage the Lovász raw form (with the leading `if hi : ... then ... else
  -- true = true`) as a clean `∀ i hi → integer Lovász holds at slot i`.
  have hlovasz : ∀ (i : Nat) (hi : i + 1 < n),
      (δ.den : Int) *
          (((Hex.GramSchmidt.Int.data b).d.get
              ⟨i + 2, Nat.succ_lt_succ hi⟩ : Int) *
              ((Hex.GramSchmidt.Int.data b).d.get
                ⟨i, Nat.lt_succ_of_lt
                  (Nat.lt_trans (Nat.lt_succ_self i) hi)⟩ : Int) +
            (((Hex.GramSchmidt.Int.data b).ν.get ⟨i + 1, hi⟩).get
              ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩) ^ 2) ≥
        δ.num *
          ((Hex.GramSchmidt.Int.data b).d.get
            ⟨i + 1, Nat.succ_lt_succ
              (Nat.lt_trans (Nat.lt_succ_self i) hi)⟩ : Int) ^ 2 := by
    intro i hi
    have h := hlovasz_raw ⟨i, Nat.lt_trans (Nat.lt_succ_self i) hi⟩
    simp only [hi, dite_true, decide_eq_true_eq] at h
    exact h
  refine ⟨?_, hindep⟩
  refine ⟨?_, ?_⟩
  · -- Size-reduced part of `isLLLReduced`.
    intro i j hi hji
    -- The `hsize` clause, specialized at i (with proof hi) and j (with proof hji).
    have hint := hsize ⟨i, hi⟩ ⟨j, hji⟩
    -- Need positivity of d[j+1] from independence.
    have hd_pos : 0 < (Hex.GramSchmidt.Int.data b).d.get
        ⟨j + 1, Nat.succ_lt_succ (Nat.lt_trans hji hi)⟩ :=
      hdPos ⟨j, Nat.lt_trans hji hi⟩
    -- Apply the size-square bridge.
    exact sizeSq_of_intCheck b δ η hi hji hd_pos hint
  · -- Lovász part.
    intro i hi
    exact lovasz_of_intCheck b δ η hi hindep (hlovasz i hi)

/-- Soundness of the dispatched reducedness clause `Hex.lllReducedCheck`:
whichever side decided — the fixed-precision interval checker
(`HexLLLMathlib.lllReducedInterval_sound`), the exact integer checker
chosen by the size predictor, or the exact fallback after interval
indecision (both via `lllReducedInt_sound` above) — acceptance entails
the rational `isLLLReduced` predicate and independence. The predictor
`Hex.intervalWins` only selects between sound checkers, so no hypothesis
about it is needed. -/
theorem lllReducedCheck_sound (b : Hex.Matrix Int n m) (δ η : Rat) :
    Hex.lllReducedCheck b δ η = true →
      Hex.isLLLReduced b δ η ∧ Hex.Matrix.independent b := by
  intro hcheck
  unfold Hex.lllReducedCheck at hcheck
  simp only [Hex.withRecordCheckerOutcome] at hcheck
  by_cases hwin : Hex.intervalWins b = true
  · rw [if_pos hwin] at hcheck
    by_cases hint : Hex.lllReducedInterval b δ η = true
    · exact HexLLLMathlib.lllReducedInterval_sound b δ η hint
    · rw [if_neg (by simpa using hint)] at hcheck
      exact lllReducedInt_sound b δ η hcheck
  · rw [if_neg (by simpa using hwin)] at hcheck
    exact lllReducedInt_sound b δ η hcheck

/-- Soundness of the certified-dispatch checker `Hex.certCheck`: an accepted
certificate `(B', U, V)` proves that `B` and `B'` generate the same integer row
lattice, that `B'` is independent, and that `B'` is `(δ, η)`-LLL-reduced.

Composes the two soundness ingredients:
* `Hex.Matrix.sameLatticeCert_sound` (Mathlib-free, HexLLL/Basic.lean) for the
  same-lattice clause, and
* `lllReducedCheck_sound` (above) for independence and reducedness, covering
  both the interval decision and the exact integer fallback.

No validity hypothesis on `η`: the `1/2 ≤ η`, `η² < δ` conditions for the LLL
short-vector bound live on `short_vector_bound_of_size_bound`, not on the
checker. This is the single trusted soundness theorem feeding the
certified-dispatch correctness of `lll`. -/
theorem certCheck_sound {B B' : Hex.Matrix Int n m} {U V : Hex.Matrix Int n n}
    {δ η : Rat} :
    Hex.certCheck B B' U V δ η = true →
      (∀ v, B.memLattice v ↔ B'.memLattice v) ∧
        B'.independent ∧ Hex.isLLLReduced B' δ η := by
  intro hcheck
  unfold Hex.certCheck at hcheck
  simp only [Bool.and_eq_true] at hcheck
  obtain ⟨hsame, hred⟩ := hcheck
  refine ⟨Hex.Matrix.sameLatticeCert_sound hsame, ?_, ?_⟩
  · exact (lllReducedCheck_sound B' δ η hred).2
  · exact (lllReducedCheck_sound B' δ η hred).1

end HexLLLMathlib
