/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexLLL.Basic
public import HexGramSchmidtMathlib.Int
public import HexRowReduceMathlib.RankSpanNullspace
public import Mathlib.Analysis.InnerProductSpace.GramSchmidtOrtho

public section

/-!
The executable-to-Mathlib correspondence: the integer row lattice as a
`Submodule ℤ`, its identification with `Hex.Matrix.memLattice`, the
`EuclideanSpace` embeddings with their norm transport, and the conditional
Euclidean short-vector bound for an already-reduced basis.
-/

namespace HexLLLMathlib

/-- The Mathlib `Submodule ℤ` generated by the rows of an executable integer
matrix. -/
@[expose]
def latticeSubmodule (b : Hex.Matrix Int n m) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))

theorem mem_latticeSubmodule_iff (b : Hex.Matrix Int n m) (v : Vector Int m) :
    HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b ↔ Hex.Matrix.memLattice b v := by
  unfold latticeSubmodule Hex.Matrix.memLattice
  rw [Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    refine ⟨HexMatrixMathlib.vectorEquiv.symm c,
      HexMatrixMathlib.vectorEquiv.injective ?_⟩
    rw [HexMatrixMathlib.vectorEquiv_rowCombination,
      Fintype.linearCombination_apply, Equiv.apply_symm_apply]
    refine (Finset.sum_congr rfl fun i _ => ?_).trans hc
    rw [HexMatrixMathlib.matrixEquiv_row]
  · rintro ⟨c, hc⟩
    refine ⟨HexMatrixMathlib.vectorEquiv c, ?_⟩
    have hr := HexMatrixMathlib.vectorEquiv_rowCombination b c
    rw [hc, Fintype.linearCombination_apply] at hr
    rw [hr]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [HexMatrixMathlib.matrixEquiv_row]

theorem memLattice_iff_mem_latticeSubmodule (b : Hex.Matrix Int n m) (v : Vector Int m) :
    Hex.Matrix.memLattice b v ↔ HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b :=
  (mem_latticeSubmodule_iff b v).symm

theorem row_mem_latticeSubmodule (b : Hex.Matrix Int n m) (i : Fin n) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ latticeSubmodule b := by
  exact Submodule.subset_span (Set.mem_range_self i)

/-- The submodule generated by rows whose indices are strictly below `t`. -/
@[expose]
def prefixSubmodule (b : Hex.Matrix Int n m) (t : Nat) : Submodule ℤ (Fin m → ℤ) :=
  Submodule.span ℤ (Set.range fun i : {i : Fin n // i.val < t} =>
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i.1))

theorem row_mem_prefixSubmodule (b : Hex.Matrix Int n m) (t : Nat)
    (i : Fin n) (hi : i.val < t) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i) ∈ prefixSubmodule b t := by
  exact Submodule.subset_span ⟨⟨i, hi⟩, rfl⟩

theorem prefixSubmodule_le_latticeSubmodule (b : Hex.Matrix Int n m) (t : Nat) :
    prefixSubmodule b t ≤ latticeSubmodule b := by
  refine Submodule.span_le.mpr ?_
  rintro _ ⟨i, rfl⟩
  exact row_mem_latticeSubmodule b i.1

private theorem rowCombination_mem_prefixSubmodule (b : Hex.Matrix Int n m)
    (c : Fin n → ℤ) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c i = 0) :
    (Fintype.linearCombination ℤ
        (fun i : Fin n => HexMatrixMathlib.vectorEquiv (Hex.Matrix.row b i))) c ∈
      prefixSubmodule b t := by
  rw [Fintype.linearCombination_apply]
  refine Submodule.sum_mem _ ?_
  intro i _hi
  by_cases hit : i.val < t
  · exact Submodule.smul_mem _ (c i) (row_mem_prefixSubmodule b t i hit)
  · have hci : c i = 0 := hc i (Nat.le_of_not_gt hit)
    simp [hci]

theorem rowCombination_mem_prefixSubmodule_of_vector (b : Hex.Matrix Int n m)
    (c : Vector Int n) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c[i] = 0) :
    HexMatrixMathlib.vectorEquiv (Hex.Matrix.rowCombination b c) ∈ prefixSubmodule b t := by
  rw [HexMatrixMathlib.vectorEquiv_rowCombination]
  exact rowCombination_mem_prefixSubmodule b (HexMatrixMathlib.vectorEquiv c) t
    (fun i hi => by simpa [HexMatrixMathlib.vectorEquiv] using hc i hi)

private theorem prefixRowCombination_memLattice (b : Hex.Matrix Int n m)
    (c : Vector Int n) (t : Nat) (hc : ∀ i : Fin n, t ≤ i.val → c[i] = 0) :
    Hex.Matrix.memLattice b (Hex.Matrix.rowCombination b c) := by
  apply (mem_latticeSubmodule_iff b _).mp
  simpa using
    prefixSubmodule_le_latticeSubmodule b t
      (rowCombination_mem_prefixSubmodule_of_vector b c t hc)

/-- View an executable integer row as a vector in Mathlib's standard Euclidean
space on `Fin m`. -/
@[expose]
def intRowToEuclidean (row : Vector Int m) : EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun j : Fin m => (row[j] : ℝ))

/-- View a Mathlib-side integer lattice vector in Mathlib's standard Euclidean
space on `Fin m`. -/
@[expose]
def intVectorToEuclidean (x : Fin m → ℤ) : EuclideanSpace ℝ (Fin m) :=
  WithLp.toLp 2 (fun j : Fin m => (x j : ℝ))

private theorem foldl_finRange_eq_sum {R : Type*} [AddCommMonoid R] {n : Nat}
    (f : Fin n → R) :
    (List.finRange n).foldl (fun acc i => acc + f i) 0 = ∑ i, f i := by
  rw [← List.foldl_map, ← List.sum_eq_foldl,
    ← List.sum_toFinset f (List.nodup_finRange n), List.toFinset_finRange]

/-- The Euclidean squared norm of an integer row embedded into
`EuclideanSpace ℝ (Fin m)` equals the real cast of the executable integer
squared norm. -/
private theorem norm_sq_intRowToEuclidean (row : Vector Int m) :
    ‖intRowToEuclidean row‖ ^ 2 = ((row.normSq : Int) : ℝ) := by
  rw [EuclideanSpace.real_norm_sq_eq]
  simp only [intRowToEuclidean, PiLp.toLp_apply]
  unfold Vector.normSq Vector.dotProduct
  rw [foldl_finRange_eq_sum]
  push_cast
  refine Finset.sum_congr rfl ?_
  intro i _
  ring

/-- The Euclidean squared norm of a lattice vector embedded into
`EuclideanSpace ℝ (Fin m)` equals the real cast of the executable integer
squared norm of its `Vector` preimage. -/
theorem norm_sq_intVectorToEuclidean (x : Fin m → ℤ) :
    ‖intVectorToEuclidean x‖ ^ 2 =
      (((HexMatrixMathlib.vectorEquiv.symm x).normSq : Int) : ℝ) := by
  have heq :
      intVectorToEuclidean x =
        intRowToEuclidean (HexMatrixMathlib.vectorEquiv.symm x) := by
    unfold intVectorToEuclidean intRowToEuclidean HexMatrixMathlib.vectorEquiv
    ext j
    simp [Vector.getElem_ofFn]
  rw [heq, norm_sq_intRowToEuclidean]

/-- Mathlib-Euclidean-norm formulation of the LLL short-vector guarantee for
an already `(δ, η)`-LLL-reduced executable basis.

The input vector is assumed to lie in the Mathlib `latticeSubmodule`.  The
proof route converts that hypothesis back through `mem_latticeSubmodule_iff`,
applies the executable `Hex.short_vector_bound_of_size_bound` for the
rational squared-norm inequality, then transports both sides through the
concrete Euclidean norm coercions above.

Consumed downstream at `η = 11/20` for the public `Hex.lll` headline
(`α = 1/(δ − 121/400)`, precondition `121/400 < δ`); also at `η = 1/2` for
the native `Hex.lllNative` classical statement (`α = 1/(δ − 1/4)`,
precondition `1/4 < δ`). -/
theorem reduced_first_row_norm_sq_le
    (b : Hex.Matrix Int n m) (δ η : Rat)
    (hη : (1 : Rat) / 2 ≤ η) (hδη : η * η < δ) (hδ' : δ ≤ 1) (hn : 1 ≤ n)
    (hli : Hex.Matrix.independent b) (hred : Hex.isLLLReduced b δ η)
    (x : Fin m → ℤ) (hx : x ∈ latticeSubmodule b) (hx0 : x ≠ 0) :
    ‖intRowToEuclidean (Hex.Matrix.row b ⟨0, Nat.lt_of_lt_of_le Nat.zero_lt_one hn⟩)‖ ^ 2 ≤
      (((1 / (δ - η * η)) ^ (n - 1) : Rat) : ℝ) *
        ‖intVectorToEuclidean x‖ ^ 2 := by
  let v : Vector Int m := HexMatrixMathlib.vectorEquiv.symm x
  have hxExec : Hex.Matrix.memLattice b v := by
    have hx' : HexMatrixMathlib.vectorEquiv v ∈ latticeSubmodule b := by
      simpa [v] using hx
    exact (mem_latticeSubmodule_iff b v).mp hx'
  have hx0Exec : v ≠ 0 := by
    intro hv
    apply hx0
    have hv' : HexMatrixMathlib.vectorEquiv v = 0 := by
      ext j
      simp [hv]
    simpa [v] using hv'
  have hRat := Hex.short_vector_bound_of_size_bound b hli hred hη hδη hδ' hn
    hxExec hx0Exec
  have hReal := (Rat.cast_le (K := ℝ)).mpr hRat
  rw [norm_sq_intRowToEuclidean, norm_sq_intVectorToEuclidean]
  simp only [Rat.cast_mul, Rat.cast_intCast] at hReal
  exact hReal

end HexLLLMathlib
